.PHONY: clean All

All:
	@echo "----------Building project:[ InputOutput - Debug ]----------"
	@cd "InputOutput" && "$(MAKE)" -f  "InputOutput.mk"
clean:
	@echo "----------Cleaning project:[ InputOutput - Debug ]----------"
	@cd "InputOutput" && "$(MAKE)" -f  "InputOutput.mk" clean
